# Generated by Django 2.2.7 on 2019-12-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0003_userprofile_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='mtype',
            field=models.CharField(choices=[('T', 'TXT'), ('P', 'IMAGINE'), ('V', 'VIDEO')], default='T', max_length=2),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='mtype',
            field=models.CharField(choices=[('T', 'TXT'), ('P', 'IMAGINE'), ('V', 'VIDEO')], default='T', max_length=2),
        ),
    ]
