# Generated by Django 2.2.7 on 2019-12-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0005_saveimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveimage',
            name='image_file',
            field=models.ImageField(height_field=150, upload_to='images/%Y', width_field=200),
        ),
    ]
