# Generated by Django 2.2.7 on 2019-12-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0006_auto_20191212_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveimage',
            name='image_file',
            field=models.ImageField(upload_to='images/%Y'),
        ),
    ]
