# Generated by Django 3.0 on 2019-12-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0007_auto_20191212_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='mtype',
            field=models.CharField(choices=[('T', 'TXT'), ('P', 'IMAGINE'), ('V', 'VIDEO'), ('I', 'EMOJI')], default='T', max_length=2),
        ),
    ]
