"""
Django settings for SampleIM project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...), This is a project's path.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'hrrm$50evd&uyh_8*76*=po^((hw5%3_$a9gq=f@xqy-rt@xj7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','172.16.2.88']

# 浏览器关闭，session 失效
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 登录或退出后的重定向界面
LOGIN_REDIRECT_URL = '/im/getLogin/'  # https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-LOGOUT_REDIRECT_URL
# LOGOUT_REDIRECT_URL = '/im/getLogout/'


# Application definition

INSTALLED_APPS = [
    'im.apps.ImConfig', # 安装 app
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'imapi.apps.ImapiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # add myself https://djangosnippets.org/snippets/10617/
    'SampleIM.middleware.OnlineNowMiddleware',
]

# https://docs.djangoproject.com/zh-hans/2.2/topics/http/urls/
ROOT_URLCONF = 'SampleIM.urls' # 网站确定根目录

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'SampleIM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# MySQL
DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.mysql',

        'NAME': 'sampleim',

        'USER': 'im',

        'PASSWORD': 'password',

        'HOST': 'localhost',

        'PORT': '3306',

        'OPTIONS':{

        'charset':'utf8mb4',

        } } }

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# 当定位到 STATIC_ROOT 的静态文件时，使用的 url。
STATIC_URL = '/static/'
# 部署时收集静态文件的文件夹的绝对路径，且该目录初始时应该为空。
STATIC_ROOT = os.path.join(BASE_DIR,'static') 
"""
django.contrib.staticfiles 安装在 INSTALLED_APPS. 
django 模板标签中的 static 标签：
 1 在部署后为  STATIC_ROOT 指定的路径；由  STATICFILES_STORAGE 管理。
 2 在部署前由 STATICFILES_STORAGE 管理， 你的工程可能包含未与任何应用绑定的静态资源。
   除了在 apps 中使用 static/ 目录，(在多 app 中，为了 django 识别，推荐 static/my_app_name/ 目录)。
   你可以在配置文件中定义一个目录列表 (STATICFILES_DIRS) ，Django 会从中寻找静态文件。
 3 备注：参考 STATICFILES_FINDERS 配置的文档了解 staticfiles 是如何找到你的文件的细节。如下：
   1 The default will find files stored in the STATICFILES_DIRS setting 
     (using django.contrib.staticfiles.finders.FileSystemFinder) and 
   2 in a static subdirectory of each app (using django.contrib.staticfiles.finders.AppDirectoriesFinder). 
     If multiple files with the same name are present, the first file that is found will be used.
"""
# 保存用户上传文件的文件系统绝对路径
MEDIA_ROOT = os.path.join(BASE_DIR,'media') 
MEDIA_URL = '/media/'
